name: subhkl
channels:
  - conda-forge
  - mantid/label/nightly
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - pycifrw
  - h5py
  - pytest
  - pydata-sphinx-theme
  - numpydoc
  - mantidworkbench
