import numpy as np
from typing import List

def run_index(
    peaks_h5_filename: str,
    output_peaks_filename: str,
    a: float | None = None,
    b: float | None = None,
    c: float | None = None,
    alpha: float | None = None,
    beta: float | None = None,
    gamma: float | None = None,
    space_group: str | None = None,
    wavelength_min: float | None = None,
    wavelength_max: float | None = None,
    ki_vec: list[float] | np.ndarray | None = None,
    original_nexus_filename: str | None = None,
    instrument_name: str | None = None,
    strategy_name: str = "DE",
    sigma_init: float | None = None,
    n_runs: int = 1,
    population_size: int = 1000,
    gens: int = 100,
    seed: int = 0,
    tolerance_deg: float = 0.1,
    freeze_orientation: bool = False,
    refine_lattice: bool = False,
    lattice_bound_frac: float = 0.05,
    refine_goniometer: bool = False,
    refine_goniometer_axes: list[str] | None = None,
    goniometer_bound_deg: float = 5.0,
    refine_sample: bool = False,
    sample_bound_meters: float = 0.005,
    refine_beam: bool = False,
    beam_bound_deg: float = 1.0,
    refine_detector: bool = False,
    refine_detector_banks: list[int] | None = None,
    detector_modes: list[str] | None = None,
    detector_trans_bound_meters: float = 0.005,
    detector_rot_bound_deg: float = 1.0,
    detector_global_rot_bound_deg: float = 2.0,
    detector_global_rot_axis: list[float] | np.ndarray | None = None,
    detector_global_trans_bound_meters: float = 0.01,
    detector_radial_bound_frac: float = 0.05,
    bootstrap_filename: str | None = None,
    batch_size: int | None = None,
    input_data: dict | None = None,
    num_candidates: int | None = None,
):
    from subhkl.io.commands import index
    return index.run(
        peaks_h5_filename,
        output_peaks_filename,
        a,
        b,
        c,
        alpha,
        beta,
        gamma,
        space_group,
        wavelength_min,
        wavelength_max,
        ki_vec,
        original_nexus_filename,
        instrument_name,
        strategy_name,
        sigma_init,
        n_runs,
        population_size,
        gens,
        seed,
        tolerance_deg,
        freeze_orientation,
        refine_lattice,
        lattice_bound_frac,
        refine_goniometer,
        refine_goniometer_axes,
        goniometer_bound_deg,
        refine_sample,
        sample_bound_meters,
        refine_beam,
        beam_bound_deg,
        refine_detector,
        refine_detector_banks,
        detector_modes,
        detector_trans_bound_meters,
        detector_rot_bound_deg,
        detector_global_rot_bound_deg,
        detector_global_rot_axis,
        detector_global_trans_bound_meters,
        detector_radial_bound_frac,
        bootstrap_filename,
        batch_size,
        input_data,
        num_candidates,
    )



def run_finder(
    filename: str,
    instrument: str,
    output_filename: str = "output.h5",
    finder_algorithm: str = "peak_local_max",
    show_progress: bool = True,
    create_visualizations: bool = False,
    show_steps: bool = False,
    peak_local_max_min_pixel_distance: int = -1,
    peak_local_max_min_relative_intensity: float = -1,
    peak_local_max_normalization: bool = False,
    mask_file: str | None = None,
    mask_rel_erosion_radius: float | None = None,
    thresholding_noise_cutoff_quantile: float = 0.8,
    thresholding_min_peak_dist_pixels: float = 8.0,
    thresholding_blur_kernel_sigma: int = 5,
    thresholding_open_kernel_size_pixels: int = 3,
    wavelength_min: float | None = None,
    wavelength_max: float | None = None,
    region_growth_distance_threshold: float = 1.5,
    region_growth_minimum_sigma: float | None = None,
    region_growth_minimum_intensity: float = 4500.0,
    region_growth_maximum_pixel_radius: float = 17.0,
    peak_center_box_size: int = 15,
    peak_smoothing_window_size: int = 15,
    peak_minimum_pixels: int = 30,
    peak_minimum_signal_to_noise: float = 1.0,
    peak_pixel_outlier_threshold: float = 2.0,
    sparse_rbf_alpha: float = 0.1,
    sparse_rbf_gamma: float = 1.0,
    sparse_rbf_min_sigma: float = 1.5,
    sparse_rbf_max_sigma: float = 10.0,
    sparse_rbf_max_peaks: int = 500,
    sparse_rbf_chunk_size: int = 512,
    sparse_rbf_tile_rows: int = 2,
    sparse_rbf_tile_cols: int = 2,
    sparse_rbf_loss: str = "gaussian",
    sparse_rbf_auto_tune_alpha: bool = False,
    sparse_rbf_candidate_alphas: str = "3.0,5.0,10.0,15.0,20.0,25.0,30",
    max_workers: int = 16,
):
    from subhkl.io.commands import finder
    return finder.run(
        filename,
        instrument,
        output_filename,
        finder_algorithm,
        show_progress,
        create_visualizations,
        show_steps,
        peak_local_max_min_pixel_distance,
        peak_local_max_min_relative_intensity,
        peak_local_max_normalization,
        mask_file,
        mask_rel_erosion_radius,
        thresholding_noise_cutoff_quantile,
        thresholding_min_peak_dist_pixels,
        thresholding_blur_kernel_sigma,
        thresholding_open_kernel_size_pixels,
        wavelength_min,
        wavelength_max,
        region_growth_distance_threshold,
        region_growth_minimum_sigma,
        region_growth_minimum_intensity,
        region_growth_maximum_pixel_radius,
        peak_center_box_size,
        peak_smoothing_window_size,
        peak_minimum_pixels,
        peak_minimum_signal_to_noise,
        peak_pixel_outlier_threshold,
        sparse_rbf_alpha,
        sparse_rbf_gamma,
        sparse_rbf_min_sigma,
        sparse_rbf_max_sigma,
        sparse_rbf_max_peaks,
        sparse_rbf_chunk_size,
        sparse_rbf_tile_rows,
        sparse_rbf_tile_cols,
        sparse_rbf_loss,
        sparse_rbf_auto_tune_alpha,
        sparse_rbf_candidate_alphas,
        max_workers,
    )



def run_peak_predictor(
    filename: str,
    instrument: str,
    indexed_hdf5_filename: str,
    integration_peaks_filename: str,
    d_min: float = 1.0,
    create_visualizations: bool = False,
    space_group: str | None = None,
    wavel_min: float | None = None,
    wavel_max: float | None = None,
    max_workers: int = 16,
):
    from subhkl.io.commands import predictor
    return predictor.run(
        filename,
        instrument,
        indexed_hdf5_filename,
        integration_peaks_filename,
        d_min,
        create_visualizations,
        space_group,
        wavel_min,
        wavel_max,
        max_workers,
    )

def run_metrics(
    file1: str,
    file2: str | None = None,
    instrument: str | None = None,
    d_min: float | None = None,
    per_run: bool = False,
    ki_vec: List[float] | np.ndarray = None,
):
    from subhkl.io.commands import metrics
    return metrics.run(file1, file2, instrument, d_min, per_run, ki_vec)

def run_rbf_integrator(
    filename: str,
    instrument: str,
    integration_peaks_filename: str,
    output_filename: str,
    alpha: float = 1.0,
    gamma: float = 1.0,
    sigmas: str = "1.0,2.0,4.0",
    nominal_sigma: float = 1.0,
    anisotropic: bool = False,
    fit_mosaicity: bool = False,
    max_peaks: int = 500,
    rel_border_width: float = 0.0,
    show_progress: bool = True,
    create_visualizations: bool = False,
    chunk_size: int = 256,
    max_workers: int | None = None,
):
    from subhkl.io.commands import integrator
    return integrator.run_rbf(
        filename,
        instrument,
        integration_peaks_filename,
        output_filename,
        alpha,
        gamma,
        sigmas,
        nominal_sigma,
        anisotropic,
        fit_mosaicity,
        max_peaks,
        rel_border_width,
        show_progress,
        create_visualizations,
        chunk_size,
        max_workers,
    )

def run_integrator(
    filename: str,
    instrument: str,
    integration_peaks_filename: str,
    output_filename: str,
    integration_method: str = "free_fit",
    integration_mask_file: str | None = None,
    integration_mask_rel_erosion_radius: float | None = 0.05,
    region_growth_distance_threshold: float = 1.5,
    region_growth_minimum_intensity: float = 50.0,
    region_growth_minimum_sigma: float | None = None,
    region_growth_maximum_pixel_radius: float = 17.0,
    peak_center_box_size: int = 15,
    peak_smoothing_window_size: int = 15,
    peak_minimum_pixels: int = 10,
    peak_minimum_signal_to_noise: float = 1.0,
    peak_pixel_outlier_threshold: float = 2.0,
    create_visualizations: bool = False,
    show_progress: bool = True,
    found_peaks_file: str | None = None,
    max_workers: int = 16,
):
    from subhkl.io.commands import integrator
    return integrator.run(
        filename,
        instrument,
        integration_peaks_filename,
        output_filename,
        integration_method,
        integration_mask_file,
        integration_mask_rel_erosion_radius,
        region_growth_distance_threshold,
        region_growth_minimum_intensity,
        region_growth_minimum_sigma,
        region_growth_maximum_pixel_radius,
        peak_center_box_size,
        peak_smoothing_window_size,
        peak_minimum_pixels,
        peak_minimum_signal_to_noise,
        peak_pixel_outlier_threshold,
        create_visualizations,
        show_progress,
        found_peaks_file,
        max_workers,
    )

def run_mtz_exporter(
    indexed_h5_filename: str, output_mtz_filename: str, space_group: str = None
):
    from subhkl.io.export import MTZExporter
    algorithm = MTZExporter(indexed_h5_filename, space_group)
    algorithm.write_mtz(output_mtz_filename)

def run_reduce(
    nexus_filename: str,
    output_filename: str,
    instrument: str,
    wavelength_min: float | None = None,
    wavelength_max: float | None = None,
):
    from subhkl.io.commands import reduce

    return reduce.run(
        nexus_filename,
        output_filename,
        instrument,
        wavelength_min,
        wavelength_max
    )


def run_merge_images(
    input_pattern: str,
    output_filename: str,
    a: float,
    b: float,
    c: float,
    alpha: float,
    beta: float,
    gamma: float,
    space_group: str,
):
    from subhkl.io.commands import merge_images

    return merge_images.run(
        input_pattern, output_filename, a, b, c, alpha, beta, gamma, space_group
    )


def run_zone_axis_search(
    merged_h5_filename: str,
    peaks_h5_filename: str,
    instrument: str,
    output_h5_filename: str,
    space_group: str = None,
    d_min: float = 1.0,
    vector_tolerance: float = 0.15,
    border_frac: float = 0.1,
    min_intensity: float = 50.0,
    hough_grid_resolution: int = 1024,
    n_hough: int = 15,
    davenport_angle_tol: float = 0.5,
    top_k_rays: int = 15,
    max_uvw: int = 25,
    L_max: float = 250.0,
    top_k: int = 1000,
    num_runs: int = 0,
    output_hough: str | None = None,
    batch_size: int = 1024,
):
    from subhkl.io.commands import zone_axis_search

    return zone_axis_search.run(
        merged_h5_filename,
        peaks_h5_filename,
        instrument,
        output_h5_filename,
        space_group,
        d_min,
        vector_tolerance,
        border_frac,
        min_intensity,
        hough_grid_resolution,
        n_hough,
        davenport_angle_tol,
        top_k_rays,
        max_uvw,
        L_max,
        top_k,
        num_runs,
        output_hough,
        batch_size,
    )
