name: CI

on:
  push:
    branches:
      - '*' 
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Linting + formating
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.10"
          cache: true
      - name: Install dependencies
        run: |
          pdm venv create --with-pip --force $PYTHON
          pdm sync --dev -G:all
      - run: |
          pdm run ruff format --check
          pdm run ruff check

  test-unit:
    name: Unit tests
    strategy:
      matrix:
        python-version: ["3.10"]
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
      - name: Install dependencies
        run: |
          pdm venv create --with-pip --force $PYTHON
          pdm sync --dev -G:all
      - run: pdm run pytest 
