name: Docker build

on:
  push:
    branches: ['main', 'docker']

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Download repo
        uses: actions/checkout@v4

      - name: Code ornl gov login
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: code.ornl.gov:4567
          password: ${{ secrets.rse_mantid_docker_token }}
          username: ${{ secrets.rse_mantid_docker_username }}

      - name: Login
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ github.actor }}

      - name: Create image name
        id: name
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          labels: ${{ steps.name.outputs.labels }}
          push: true
          tags: ${{ steps.name.outputs.tags }}
